### ISSUE TITLE
install_packages redirects output to /dev/null

### ISSUE THREAD

**Issue by gladykov** [isort/isort-action#28]
Hey!

Any reason why install_packages redirects output to /dev/null https://github.com/isort/isort-action/blob/master/bin/install_packages ? I had some issue with isort and setuptools and other packages, and lack of output slowed down my debug process. Are you open to remove that redirection and use stdout and stderr instead ?

**Comment by jamescurtin** [comment]
Yes! This was originally done to keep the log output clean. If you were willing to make a PR for this issue, perhaps you could use [Github Action's log line grouping](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines) functionality so that the pip install output can be folded and hidden?

**Comment by gladykov** [comment]
#29  :)
